apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster     
  namespace: kafka-oauth
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
      tls:
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          validIssuerUri: https://sso-sso.apps.ocp.myocp.net/auth/realms/openshift
          jwksEndpointUri: https://sso-sso.apps.ocp.myocp.net/auth/realms/openshift/protocol/openid-connect/certs
          userNameClaim: azp
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt   
    logging:
      type: inline
      loggers:
        log4j.logger.io.strimzi: "DEBUG"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 4Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 4Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
